name: "Analytics coverage check"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - feature/analytics-coverage

jobs:
  audit:
    name: Audit analytics instrumentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run analytics coverage (strict)
        run: npm run check:analytics -- --strict
